### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by EzequielVilla** [Lio-n/dwf-m10-desafio#1]
Buenas!
No tengo mucho para decir del desafio, la verdad que esta muy bien la ux/ui e incluso el codigo. A destacar:

- Esta todo tipado (o casi todo no vi tan bien).
- Guardas la data en el server para cuando alguien selecciona un item
- La capa ui esta prolija
- Los custom hooks son simples, al igual que las pages
- Los components hacen lo minimo y necesario
- El uso de skeletons para que el user sepa que algo esta pasando

En fin, la verdad que hiciste un laburo muy bueno, muy prolijo y super destacable! Exitos en los siguientes modulos!!

**Comment by Lio-n** [comment]
Buenas, @EzequielVilla 
Muchas Gracias! 🤙
